version: '3.8'

services:
  # Spring Boot应用
  app:
    build: .
    container_name: spring-demo-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/springdemo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - spring-network

  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: spring-demo-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=springdemo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - spring-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: spring-demo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - spring-network

volumes:
  mysql_data:

networks:
  spring-network:
    driver: bridge 